import { Providers } from "@/components/Providers";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      
      <body className="bg-gray-50 dark:bg-slate-800">
        <Providers>
          <Nav/>
          <main>
          {children}
          </main>
        </Providers>
        

      </body>
    </html>
  );
}
